import { get, post, put, del } from './api'

export const adminLogin          = (d)       => fetch('/api/v1/admin/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(d) }).then(r => r.json())
export const getAdminDashboard   = ()        => get('/api/v1/admin/dashboard')
export const getAdminTenants     = (q = '')  => get(`/api/v1/admin/tenants?${q}`)
export const getAdminTenant      = (id)      => get(`/api/v1/admin/tenants/${id}`)
export const updateAdminTenant   = (id, d)   => put(`/api/v1/admin/tenants/${id}`, d)
export const suspendTenant       = (id)      => post(`/api/v1/admin/tenants/${id}/suspend`)
export const reactivateTenant    = (id)      => post(`/api/v1/admin/tenants/${id}/reactivate`)
export const upgradeTenant       = (id, d)   => post(`/api/v1/admin/tenants/${id}/upgrade`, d)
export const wipeTenantData      = (id)      => del(`/api/v1/admin/tenants/${id}/data`)
export const getFeatureFlags     = ()        => get('/api/v1/admin/feature-flags')
export const updateFeatureFlag   = (name, d) => put(`/api/v1/admin/feature-flags/${name}`, d)
export const enableFlagForTenant = (flag, d) => post('/api/v1/admin/feature-flags/tenant', { flag, ...d })
export const getAdminAnnouncements = ()      => get('/api/v1/admin/announcements')
export const createAnnouncement  = (d)       => post('/api/v1/admin/announcements', d)
export const getAdminTickets     = (q = '')  => get(`/api/v1/admin/tickets?${q}`)
export const getAdminTicket      = (id)      => get(`/api/v1/admin/tickets/${id}`)
export const replyToTicket       = (id, d)   => post(`/api/v1/admin/tickets/${id}/reply`, d)
export const getAdminMetrics     = ()        => get('/api/v1/admin/metrics')
export const getAdminTeam        = ()        => get('/api/v1/admin/team')
export const getRateLimits       = ()        => get('/api/v1/admin/rate-limits')
export const updateRateLimit     = (id, d)   => put(`/api/v1/admin/rate-limits/${id}`, d)
